/**
 * Store + generator regression tests. These run the real `ConceptStore` /
 * `ConceptGenerator` against the in-memory Obsidian stub
 * (`npm test` aliases `obsidian` to `tests/stub-obsidian.ts`), so no vault,
 * network or API key is involved.
 */
import { makeApp, TFile } from './stub-obsidian';
import { ConceptStore } from '../src/store';
import { ConceptGenerator } from '../src/generator';
import { computeDepths } from '../src/exporters';
import { DEFAULT_SETTINGS, type DiscoveryResult, type TreeNode, type TreeModel } from '../src/types';

let failures = 0;
function assert(cond: boolean, label: string): void {
	if (cond) {
		console.log(`  ok  ${label}`);
	} else {
		failures++;
		console.error(`FAIL  ${label}`);
	}
}
function eq(actual: unknown, expected: unknown, label: string): void {
	assert(
		actual === expected,
		`${label} (got ${JSON.stringify(actual)}, want ${JSON.stringify(expected)})`
	);
}

/** Names reachable from the root by following `children` links. */
function reachableFrom(model: TreeModel): Set<string> {
	const seen = new Set<string>();
	const walk = (name: string) => {
		if (seen.has(name)) return;
		seen.add(name);
		for (const c of model.nodes.get(name)?.children ?? []) walk(c);
	};
	walk(model.root);
	return seen;
}

const DISCOVERY: DiscoveryResult = {
	concept: 'Democracy',
	domains: [
		{
			name: 'Political Science',
			children: [
				{ name: 'Direct Democracy', description: 'People vote directly.', complexity: 'Beginner' },
				{ name: 'Representative Democracy', description: 'Elected representatives.' },
			],
		},
	],
};

let seq = 0;
/** Deterministic replacement for the API-backed expand(): N children per node. */
function stubExpand(childrenPerNode: number) {
	return async (node: TreeNode, model: TreeModel) => {
		const created: TreeNode[] = [];
		for (let i = 1; i <= childrenPerNode; i++) {
			created.push({
				name: `${node.name} ${++seq}`,
				parent: node.name,
				description: 'generated by the test stub',
				complexity: 'Beginner',
				canExpand: true,
				estimatedDepth: 3,
				connections: [],
				children: [],
				path: `${node.path}/${seq}`,
				created: 0,
				file: '',
				treeRoot: model.root,
				expanded: false,
				loading: false,
			});
		}
		for (const c of created) {
			node.children.push(c.name);
			model.nodes.set(c.name, c);
		}
		return { created, skipped: [] as string[] };
	};
}

function makeGenerator(app: any, store: ConceptStore, childrenPerNode: number): any {
	const cache: any = { get: async () => null, set: async () => undefined };
	const gen: any = new ConceptGenerator(
		app,
		store,
		{ search: () => [] } as any,
		() => DEFAULT_SETTINGS,
		cache
	);
	gen.expand = stubExpand(childrenPerNode);
	return gen;
}

async function main(): Promise<void> {
	// ---------------------------------------------------------------- delete + undo
	{
		const app = makeApp();
		const store = new ConceptStore(app);
		await store.createDiscoveryTree(DISCOVERY, 'CogniTree');
		let model = (await store.loadTree('Democracy'))!;
		await store.addChildren(
			model.nodes.get('Direct Democracy')!,
			[
				{ name: 'Referendums', description: 'Direct votes.', complexity: 'Beginner' },
				{ name: 'Citizen Assemblies', description: 'Sortition bodies.' },
			],
			'CogniTree',
			model.nodes
		);
		model = (await store.loadTree('Democracy'))!;
		eq(model.nodes.size, 5, 'tree built: root + 2 domain children + 2 grandchildren');
		eq(reachableFrom(model).size, 5, 'every node starts out reachable');

		// What ConceptTreeView.confirmDelete captures before deleting.
		const snap: { name: string; file: string; content: string }[] = [];
		for (const sub of store.collectSubtree(model, 'Direct Democracy')) {
			const ref = app.vault.getAbstractFileByPath(sub.file);
			if (ref instanceof TFile) {
				snap.push({ name: sub.name, file: sub.file, content: await app.vault.cachedRead(ref) });
			}
		}
		eq(snap.length, 3, 'delete snapshot covers the node + descendants');

		const deleted = await store.deleteSubtree(model, 'Direct Democracy');
		eq(deleted, 3, 'deleteSubtree trashes the whole subtree');
		assert(!model.nodes.has('Direct Democracy'), 'deleteSubtree drops the node from the model');
		assert(
			!model.nodes.has('Referendums') && !model.nodes.has('Citizen Assemblies'),
			'deleteSubtree drops the descendants from the model (no ghost nodes)'
		);

		// Undo: recreate the files, re-attach the node to its parent.
		for (const s of snap) {
			if (app.vault.getAbstractFileByPath(s.file) instanceof TFile) continue;
			await app.vault.create(s.file, s.content);
		}
		eq(
			await store.relinkChild(model, 'Democracy', 'Direct Democracy'),
			true,
			'relinkChild re-attaches the restored node to its parent note'
		);
		eq(await store.relinkChild(model, 'Nope', 'Nothing'), false, 'relinkChild reports a missing parent');

		const after = (await store.loadTree('Democracy'))!;
		const reachable = reachableFrom(after);
		assert(
			reachable.has('Direct Democracy') &&
				reachable.has('Referendums') &&
				reachable.has('Citizen Assemblies'),
			'restored subtree is reachable from the root again (Undo actually restores the tree)'
		);
		eq(reachable.size, after.nodes.size, 'no orphaned notes after the undo');
		eq(
			await store.relinkChild(after, 'Democracy', 'Direct Democracy'),
			false,
			'relinkChild is idempotent (no duplicate child entry)'
		);
	}

	// ---------------------------------------------------------------- batch depth
	{
		const app = makeApp();
		const store = new ConceptStore(app);
		await store.createDiscoveryTree(
			{ concept: 'Root', domains: [{ name: 'D', children: [{ name: 'A', description: 'a' }] }] },
			'CogniTree'
		);
		// Each stub expansion adds exactly 2 children, so the node count reveals
		// how many levels ran: 2, 6, 14 for 1, 2 and 3 levels.
		const added: number[] = [];
		for (const depth of [1, 2, 3]) {
			const res = await makeGenerator(app, store, 2).batch(
				'Root',
				depth,
				100,
				undefined,
				undefined,
				undefined,
				'A'
			);
			added.push(res.added);
		}
		eq(added[0], 2, 'batch(depth 1) generates two children for the start node');
		eq(added[1], 6, 'batch(depth 2) generates two levels');
		eq(added[2], 14, 'batch(depth 3) generates three levels');
	}

	// ---------------------------------------------------------------- batch budget
	{
		const app = makeApp();
		const store = new ConceptStore(app);
		await store.createDiscoveryTree(
			{ concept: 'Root', domains: [{ name: 'D', children: [{ name: 'A', description: 'a' }] }] },
			'CogniTree'
		);
		const res = await makeGenerator(app, store, 7).batch(
			'Root',
			4,
			10,
			undefined,
			undefined,
			undefined,
			'A'
		);
		// The budget cannot pre-empt expansions already in flight: with
		// CONCURRENCY (3) workers up to 3 × 7 nodes may overshoot. Without the
		// in-level check the second level runs in full: 7 + 49 = 56.
		assert(
			res.added >= 7 && res.added <= 31,
			`batch(depth 4, budget 10) stays near the budget (got ${res.added}, want 7..31)`
		);
	}

	// ---------------------------------------------------------------- depth vs `path`
	{
		const app = makeApp();
		const store = new ConceptStore(app);
		await store.createDiscoveryTree(DISCOVERY, 'CogniTree');
		const model = (await store.loadTree('Democracy'))!;
		const depths = computeDepths(model);
		eq(depths.get('Democracy'), 0, 'computeDepths: root is 0');
		eq(depths.get('Direct Democracy'), 1, 'computeDepths: domain children sit at depth 1');
		const child = model.nodes.get('Direct Democracy')!;
		assert(
			child.path.split('/').filter(Boolean).length === 3 && depths.get('Direct Democracy') === 1,
			'real depth ignores the domain slug embedded in `path`'
		);
	}

	// ---------------------------------------------------------------- duplicate concepts
	{
		const app = makeApp();
		const store = new ConceptStore(app);
		app.vault.folders.add('CogniTree');
		app.vault.folders.add('CogniTree/T');
		const note = (name: string) =>
			`---\nconcept: "${name}"\ntree: "T"\nparent: "T"\ndescription: "d"\ncomplexity: "Beginner"\n` +
			`can_expand: true\nestimated_depth: 3\nconnections: []\nchildren: []\npath: "/t"\n` +
			`created: 2025-01-01T00:00:00.000Z\n---\n# ${name}\n`;
		app.vault.files.set('CogniTree/T/T.md', note('T'));
		app.vault.files.set('CogniTree/T/Alpha (2).md', note('Alpha')); // stray copy first
		app.vault.files.set('CogniTree/T/Alpha.md', note('Alpha')); // canonical second
		const model = (await store.loadTree('T'))!;
		eq(model.nodes.size, 2, 'two notes claiming one concept load as a single node');
		eq(
			model.nodes.get('Alpha')!.file,
			'CogniTree/T/Alpha.md',
			'the canonical filename wins over a " (2)" copy'
		);
	}

	// ---------------------------------------------------------------- subtree merge
	{
		const app = makeApp();
		const store = new ConceptStore(app);
		const note = (name: string, tree: string, parent: string | null, children: string[]) =>
			`---\nconcept: "${name}"\ntree: "${tree}"\n${parent ? `parent: "${parent}"\n` : ''}` +
			`description: "d"\ncomplexity: "Beginner"\ncan_expand: true\nestimated_depth: 3\nconnections: []\n` +
			`children: [${children.map((c) => `"${c}"`).join(', ')}]\npath: "/${name.toLowerCase()}"\n` +
			`created: 2025-01-01T00:00:00.000Z\n---\n# ${name}\n`;
		app.vault.folders.add('CogniTree');
		for (const f of ['Alpha', 'Beta']) app.vault.folders.add(`CogniTree/${f}`);
		// Tree "Alpha": Alpha → {AChild → ADeep, Shared}
		app.vault.files.set('CogniTree/Alpha/Alpha.md', note('Alpha', 'Alpha', null, ['AChild', 'Shared']));
		app.vault.files.set('CogniTree/Alpha/AChild.md', note('AChild', 'Alpha', 'Alpha', ['ADeep']));
		app.vault.files.set('CogniTree/Alpha/ADeep.md', note('ADeep', 'Alpha', 'AChild', []));
		app.vault.files.set('CogniTree/Alpha/Shared.md', note('Shared', 'Alpha', 'Alpha', []));
		// Tree "Beta": Beta → {BOther, Shared, Something Else}
		app.vault.files.set(
			'CogniTree/Beta/Beta.md',
			note('Beta', 'Beta', null, ['BOther', 'Shared', 'Something Else'])
		);
		app.vault.files.set('CogniTree/Beta/BOther.md', note('BOther', 'Beta', 'Beta', []));
		app.vault.files.set('CogniTree/Beta/Shared.md', note('Shared', 'Beta', 'Beta', []));
		// Occupies the filename ADeep.md in the target with a *different* concept.
		app.vault.files.set('CogniTree/Beta/ADeep.md', note('Something Else', 'Beta', 'Beta', []));

		const alpha = (await store.loadTree('Alpha'))!;
		const beta = (await store.loadTree('Beta'))!;
		const res = await store.mergeSubtree(alpha, 'Alpha', beta, 'Beta');
		eq(res.moved, 2, 'merge moves the descendants that are new to the target tree');
		assert(
			JSON.stringify(res.skipped) === JSON.stringify(['Shared']),
			`merge reports the concept already present in the target (got ${JSON.stringify(res.skipped)})`
		);

		const betaAfter = (await store.loadTree('Beta'))!;
		const betaReachable = reachableFrom(betaAfter);
		assert(
			betaReachable.has('AChild') && betaReachable.has('ADeep'),
			'merged descendants are reachable from the target root'
		);
		eq(betaAfter.nodes.get('AChild')!.parent, 'Beta', 'merged child is re-parented to the target node');
		assert(
			app.vault.files.has('CogniTree/Beta/ADeep (2).md'),
			'a filename collision moves under a unique name instead of being skipped'
		);
		const betaDangling = [...betaAfter.nodes.values()].flatMap((n) =>
			n.children.filter((c) => !betaAfter.nodes.has(c)).map((c) => `${n.name} → ${c}`)
		);
		eq(betaDangling.length, 0, `target tree has no dangling child references (${betaDangling.join(', ')})`);

		const alphaAfter = (await store.loadTree('Alpha'))!;
		const alphaReachable = reachableFrom(alphaAfter);
		assert(
			alphaReachable.has('Shared') && !alphaReachable.has('AChild'),
			'the skipped duplicate stays behind under its original parent'
		);
		const alphaDangling = [...alphaAfter.nodes.values()].flatMap((n) =>
			n.children.filter((c) => !alphaAfter.nodes.has(c)).map((c) => `${n.name} → ${c}`)
		);
		eq(alphaDangling.length, 0, `source tree has no dangling child references (${alphaDangling.join(', ')})`);
		assert(
			app.vault.files.has('CogniTree/Alpha/Shared.md'),
			'the skipped note is not deleted from the source tree'
		);
	}

	// ---------------------------------------------------------------- cycle safety
	{
		const app = makeApp();
		const store = new ConceptStore(app);
		await store.createDiscoveryTree(DISCOVERY, 'CogniTree');
		const model = (await store.loadTree('Democracy'))!;
		// A hand-edited frontmatter cycle: Direct Democracy's child is the root.
		model.nodes.get('Direct Democracy')!.children = ['Democracy'];
		const subtree = store.collectSubtree(model, 'Democracy');
		eq(subtree.length, 3, 'collectSubtree terminates on a cycle');
		eq(computeDepths(model).size, 3, 'computeDepths terminates on a cycle');
	}
}

main()
	.then(() => {
		console.log(failures === 0 ? '\nALL STORE TESTS PASSED' : `\n${failures} TEST(S) FAILED`);
		process.exit(failures === 0 ? 0 : 1);
	})
	.catch((err) => {
		console.error('STORE TEST ERROR', err);
		process.exit(1);
	});
